apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongo-backup-cronjob
spec:
  schedule: "0 0 * * *" # Runs the job daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongo-backup
            image: mongo:latest # You can use a custom image with a script for backup
            command: ["/bin/sh"]
            args: ["-c", "mongodump --username $MONGO_BACKUP_USERNAME --password $MONGO_BACKUP_PASSWORD --out /backup && tar czvf /backup/backup_$(date +%Y%m%d_%H%M%S).tar.gz /backup"]
            env:
            - name: MONGO_BACKUP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_BACKUP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc
          - name: backup-dir
            emptyDir: {}
